plugin:
    # Set this to "true" if your plugin must have an entry in the plugin configuration page.
    has_options: 'true'
    # You can set an icon for your plugin. The icon must be in your public/images/icons folder.
    icon: 'icon.png'